### ISSUE TITLE
Uptate Smalltalk CI Workflow action to use latest stable Pharo release

### ISSUE THREAD

**Issue by Bajger** [exercism/pharo-smalltalk#527]
Currently, there is this Smalltalk CI specification: 
```
...
steps:
      - uses: actions/checkout@v2
      
      - name: Fetch smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@387e0a52e8cc6990f886fe825fd5bec8a6af9584
        id: smalltalkci
        with: 
          smalltalk-version: 'Pharo64-8.0'
```
and should be updated to:
```
      - uses: actions/checkout@v2
      
      - name: Fetch smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with: 
          smalltalk-version: 'Pharo64-9.0'
```
Details here: https://github.com/marketplace/actions/setup-smalltalkci
and here: https://github.com/hpi-swa/setup-smalltalkCI
